excluded:
  - Pods
  - .swiftformat

disabled_rules:
  - class_delegate_protocol
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - identifier_name
  - function_body_length
  - function_parameter_count
  - line_length
  - notification_center_detachment
  - type_body_length
  - valid_ibinspectable

nesting:
  type_level:
    warning: 3

type_name:
  min_length: 3
  max_length: 50
